"use client";

import { useState, useEffect } from "react";
import { FileText, RefreshCw, Loader2, Share2 } from "lucide-react";

interface ReportData {
  content: string;
  stats: {
    totalReadings: number;
    avg: number;
    highest: number;
    lowest: number;
    inRangePct: number;
    danger: number;
    fastingAvg: number | null;
    postMealAvg: number | null;
  };
  createdAt?: string;
}

export function WeeklyReportCard() {
  const [report, setReport] = useState<ReportData | null>(null);
  const [loading, setLoading] = useState(false);
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    fetch("/api/reports/weekly").then(r => r.json()).then(d => { if (d && d.content) setReport(d); });
  }, []);

  async function generate() {
    setGenerating(true);
    try {
      const res = await fetch("/api/reports/weekly", { method: "POST" });
      const data = await res.json();
      if (data.content) setReport(data);
    } catch {} finally { setGenerating(false); }
  }

  function shareReport() {
    if (!report) return;
    const text = `Sugar Buddy Weekly Report\n\nReadings: ${report.stats.totalReadings} | Avg: ${report.stats.avg} mg/dl | In Range: ${report.stats.inRangePct}%\n\n${report.content}\n\n— Generated by Sugar Buddy`;
    if (navigator.share) {
      navigator.share({ title: "Sugar Buddy Weekly Report", text });
    } else {
      navigator.clipboard.writeText(text);
      alert("Report copied to clipboard!");
    }
  }

  return (
    <div className="bg-white border border-zinc-200 rounded-xl p-4 mb-4">
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <FileText className="w-4 h-4 text-blue-600" />
          <span className="text-sm font-semibold text-zinc-900">Weekly Report</span>
        </div>
        <div className="flex items-center gap-1.5">
          {report && (
            <button onClick={shareReport} className="p-1.5 text-zinc-400 hover:text-primary rounded-lg hover:bg-zinc-50 transition-colors" title="Share">
              <Share2 className="w-3.5 h-3.5" />
            </button>
          )}
          <button onClick={generate} disabled={generating} className="inline-flex items-center gap-1 px-2.5 py-1 text-[10px] font-medium text-primary bg-primary-light rounded-lg hover:bg-emerald-100 transition-colors disabled:opacity-50">
            {generating ? <Loader2 className="w-3 h-3 animate-spin" /> : <RefreshCw className="w-3 h-3" />}
            {generating ? "Generating..." : "Generate"}
          </button>
        </div>
      </div>

      {report ? (
        <div>
          <div className="grid grid-cols-4 gap-2 mb-3">
            <div className="bg-zinc-50 rounded-lg p-2 text-center">
              <p className="text-base font-bold text-zinc-900">{report.stats.totalReadings}</p>
              <p className="text-[9px] text-zinc-400">Readings</p>
            </div>
            <div className="bg-zinc-50 rounded-lg p-2 text-center">
              <p className="text-base font-bold text-primary">{report.stats.avg}</p>
              <p className="text-[9px] text-zinc-400">Average</p>
            </div>
            <div className="bg-zinc-50 rounded-lg p-2 text-center">
              <p className="text-base font-bold text-emerald-600">{report.stats.inRangePct}%</p>
              <p className="text-[9px] text-zinc-400">In Range</p>
            </div>
            <div className="bg-zinc-50 rounded-lg p-2 text-center">
              <p className="text-base font-bold text-red-500">{report.stats.danger}</p>
              <p className="text-[9px] text-zinc-400">Danger</p>
            </div>
          </div>
          <p className="text-xs text-zinc-600 leading-relaxed whitespace-pre-line">{report.content}</p>
        </div>
      ) : (
        <p className="text-xs text-zinc-400">Abhi koi report nahi — Generate dabayein.</p>
      )}
    </div>
  );
}
