import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { HeroSection } from "@/components/HeroSection";

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen bg-white">
      <Navbar />
      <HeroSection tag="Legal" title="Terms of Service" subtitle="Please read these terms carefully before using Sugar Buddy." />

      <main className="flex-1 max-w-3xl mx-auto px-4 sm:px-6 py-12 w-full">
        <div className="space-y-6">
          <Section title="1. Acceptance of Terms">
            By creating an account or using Sugar Buddy, you agree to these Terms of Service. If you do not agree, do not use the application.
          </Section>
          <Section title="2. Description of Service">
            Sugar Buddy is a diabetes management tool that allows users to log blood glucose readings, receive AI-powered explanations in Roman Urdu, track trends, and chat with an AI assistant. Sugar Buddy is NOT a medical device, NOT FDA approved, and NOT a substitute for professional medical advice.
          </Section>
          <Section title="3. Medical Disclaimer">
            <div className="p-3 bg-amber-50 border border-amber-200 rounded-xl text-sm text-amber-800">
              <strong>IMPORTANT:</strong> Sugar Buddy does not provide medical advice. It does not diagnose conditions, prescribe medications, or calculate insulin doses. All AI content is educational only. Always follow your doctor&apos;s instructions. In a medical emergency, contact your doctor or nearest hospital.
            </div>
          </Section>
          <Section title="4. Account Registration">
            You must provide accurate information. You are responsible for your account credentials. You must be at least 13 years old. One person may not maintain more than one account.
          </Section>
          <Section title="5. Subscription & Payment">
            Sugar Buddy offers free and paid subscription tiers. Payments are processed through Stripe. Subscriptions auto-renew monthly unless cancelled. You may cancel anytime — access continues until end of billing period. Refunds are not provided for partial months.
          </Section>
          <Section title="6. Acceptable Use">
            You agree NOT to: use Sugar Buddy as a substitute for medical care, share your account, reverse-engineer the application, use AI chat for non-diabetes purposes, or upload false health data.
          </Section>
          <Section title="7. AI-Generated Content">
            AI responses are generated by third-party language models. While we strive for accuracy, AI can make mistakes. We are not liable for actions taken based on AI content. The AI is programmed to never recommend medication doses — if it does erroneously, do not follow such advice.
          </Section>
          <Section title="8. Data & Privacy">
            Your use is governed by our Privacy Policy. By using the service, you consent to data collection as described in the Privacy Policy.
          </Section>
          <Section title="9. Safety Features">
            Sugar Buddy includes automatic safety alerts for dangerously low (&lt;70 mg/dl) or high (&gt;300 mg/dl) readings. These are informational and do NOT replace emergency medical services.
          </Section>
          <Section title="10. Intellectual Property">
            All content, design, code, and branding is owned by us. You may not copy or distribute any part without written permission.
          </Section>
          <Section title="11. Limitation of Liability">
            Sugar Buddy is provided &quot;as is&quot; without warranties. We are not liable for health outcomes, data loss, or damages. Total liability is limited to the amount paid in the preceding 12 months.
          </Section>
          <Section title="12. Termination">
            We may suspend or terminate your account for violations. You may delete your account at any time. Data will be permanently deleted upon termination.
          </Section>
          <Section title="13. Changes to Terms">
            We may update these terms. Continued use after changes constitutes acceptance. Material changes will be communicated via email or in-app.
          </Section>
          <Section title="14. Governing Law">
            These terms are governed by the laws of Pakistan. Disputes shall be resolved in the courts of Lahore, Pakistan.
          </Section>
          <Section title="15. Contact">
            Questions? Email <strong>support@sugarbuddy.app</strong>
          </Section>
        </div>
      </main>

      <Footer />
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="text-base font-bold text-zinc-900 mb-2">{title}</h2>
      <div className="text-sm text-zinc-600 leading-relaxed">{children}</div>
    </div>
  );
}
